#!/usr/local/bin/python

import os
import sys
import ConfigParser as config
import Executor

if len(sys.argv) not in[2,3]:
    #print "Usage: %s OP" % (sys.argv[0].split("/")[-1],)
    print "Usage: %s OP [cloThres]" % (sys.argv[0].split("/")[-1],)
    print "OP is split, IBS, freq, IBD, statIBD, removeCloserIBD, removeDistant"
    sys.exit(-1)

OP = sys.argv[1]
if len(sys.argv)==3:
    cloThres = float(sys.argv[2])
else:
    cloThres = 0.125

lexec = Executor.Local(4)

cfg = config.ConfigParser()
cfg.read(os.path.expanduser("~/.megacfg"))
scriptDir = cfg.get("System","ibDir")
plinkDB = cfg.get("DB", "plink")

try:
    os.mkdir("ibdata")
except OSError:
    pass # Already exists

pops = {}
for l in sys.stdin:
    toks = l.rstrip().split("\t")
    try:
        pops.setdefault(toks[2], []).append([toks[0], toks[1]])
    except IndexError:
        print >>sys.stderr, "Error at:"
        print >>sys.stderr, l
        sys.exit(-1)

if OP == "split":
    for pop in pops:
        pop_ = pop.replace(" ", "_")
        fName ="ibdata/%s_lst.txt" % (pop_,)
        f = open(fName, "w")
        for indiv in pops[pop]:
            f.write(" ".join(indiv))
            f.write(" " + pop)
            f.write("\n")
        f.close()
        lexec.submit("plink", "--bfile %s --keep %s --noweb --out ibdata/%s --make-bed " % (plinkDB, fName, pop_))
    lexec.wait(True)
elif OP == "IBS":
    for pop in pops:
        pop = pop.replace(" ","_")
        lexec.submit("plink", "--bfile ibdata/%s --cluster --neighbour 1 5 --noweb --out ibdata/%s" % (pop, pop))
    lexec.wait(True)
elif OP == "IBD":
    for pop in pops:
        pop = pop.replace(" ","_")
        lexec.submit("plink", "--bfile ibdata/%s --genome --noweb --min %f --maf 0.001 --out ibdata/%s" % (pop, cloThres, pop))
    lexec.wait(True)
elif OP == "freq":
    for pop in pops:
        pop = pop.replace(" ","_")
        lexec.submit("plink", "--bfile ibdata/%s --freq --noweb --out ibdata/%s" % (pop, pop))
    lexec.wait(True)
elif OP == "statIBD":
    for pop in pops:
        pop = pop.replace(" ","_")
        f = open("ibdata/%s.genome" % (pop))
        f.readline()
        vals = []
        for l in f:
            pihat = float(filter(lambda x: x!="", l.rstrip().split(" "))[9])
            vals.append(pihat)
        vals.sort()
        cut125 = len(filter(lambda x:x<0.125, vals))
        cut15 = len(filter(lambda x:x<0.15, vals))
        cut20 = len(filter(lambda x:x<0.2, vals))
        print "%12s\t%.3f\t%.3f\t%3d\t%3d\t%3d\t%3d" % (pop, sum(vals)/len(vals), vals[len(vals)/2], len(vals), cut125, cut15, cut20)
        f.close()
elif OP == "removeCloserIBD":
    for pop in pops:
        print pop
        #os.system("nice -n19 python %s/removeCloserIBD.py ibdata/%s %f &" % (scriptDir, pop, cloThres))
        lexec.submit("python", "%s/removeCloserIBD.py %s %f" % (scriptDir, pop.replace(" ", "_"), cloThres))
    lexec.wait(True)
elif OP == "removeDistant":
    for pop in pops:
        print pop
        lexec.submit("python", "%s/removeDistant.py %s " % (scriptDir, pop.replace(" ", "_"),))
    lexec.wait(True)

