#!/usr/local/bin/python

import os
import sys
import ConfigParser as config
import MEGA

if len(sys.argv) == 2 and sys.argv[1]=="--help":
    print "Usage: %s [pop]" % (sys.argv[0].split("/")[-1],)
    sys.exit(-1)

if len(sys.argv)>1:
    pops = sys.argv[1:]
else:
    pops = None

cfg = config.ConfigParser()
cfg.read(os.path.expanduser("~/.megacfg"))
metaDB = cfg.get("DB","meta")

f = open(metaDB + os.sep + "clean.tab")
for l in f:
    rec = MEGA.getRecord(l)
    if rec["pop"] == "": continue
    if not pops or rec["pop"] in pops:
        print "\t".join([rec["sampId"], rec["famId"], rec["pop"]])
f.close()
