#!/usr/local/bin/python

import os
import sys
import ConfigParser as config
import MEGA

if len(sys.argv) <2:
    print "Usage: %s indIds..." % (sys.argv[0].split("/")[-1],)
    sys.exit(-1)

myInds = sys.argv[1:]

cfg = config.ConfigParser()
cfg.read(os.path.expanduser("~/.megacfg"))
metaDB = cfg.get("DB","meta")

indPop = MEGA.getPop4Indiv()

for ind in myInds:
    print indPop[ind]
